language: python

python: 3.5

install:
  - pip install -r requirements.txt

script:
  - py.test -v -s --durations=10 --ignore=env

notifications:
  email:
    recipients:
      - leonst998@gmail.com
    on_success: always
    on_failure: always